server:
  port: 8080

spring:
  application:
    name: gateway-service

spring:
  cloud:
    gateway:
      routes:
        - id: catalogo
          uri: http://localhost:8081
          predicates:
            - Path=/produtos/**
        - id: pedido
          uri: http://localhost:8082
          predicates:
            - Path=/pedidos/**
